CREATE USER api WITH PASSWORD 'apixptmxmtjqj01!';
GRANT CONNECT ON DATABASE dev TO api;
GRANT USAGE ON SCHEMA public TO api;
GRANT SELECT UPDATE CREATE ON ALL TABLES IN SCHEMA public TO api;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO api;